/-
  PRINCIPIA PHYSICA -- formal/drafts/Proofs.lean

  Representative Lean 4 formal skeleton accompanying the synthesis paper
  "Layered Composition, Reciprocity, and Protocol-Relative Realization".

  SCOPE AND HONEST LIMITS OF THIS FILE.

  This development is deliberately Mathlib-free: it is checked by a bare
  `lean` toolchain (Lean 4.33.0) with no external dependency.  Consequently
  it formalizes only the ORDER-AND-LOGIC SKELETON of the papers:

    * typed systems, typed processes, and their category laws;
    * parallel (product) composition and its functoriality;
    * nondegeneracy as an abstract bijection, and the exact sense in which
      an *additive* generator yields a *factorized* generator;
    * the separability/coupling distinction and its scalar trichotomy;
    * protocols, protocol-relative observational equivalence, transported
      interpretation, and protocol-relative falsification status.

  It does NOT formalize: smooth manifolds, differential forms, the closedness
  condition d(omega) = 0, de Rham cohomology, flows of vector fields, or any
  analytic limit.  Every statement below whose informal counterpart lives in
  differential geometry is therefore an ABSTRACTION of that counterpart, with
  the geometric content replaced by an explicitly declared interface
  (`Nondeg`, `Separable`).  Nothing here should be read as a machine-checked
  proof of the symplectic theorems of the source papers.

  Claim identifiers in comments refer to the synthesis paper:
    CS = compositional-systems, HR = hamiltonian-reconstruction,
    EL = empirical-limits, S = synthesis.
-/

namespace Principia

/-! ## 0. Epistemic labels

The epistemic contract requires that every substantial claim carry a type.
We reify the twelve admitted labels so that the registry at the end of this
file can be machine-checked for well-formedness (no dangling dependency). -/

inductive Label where
  | defn | axiomL | assum | conj | lem | prop | thm | cor
  | interp | empirical | established | newResult
  deriving Repr, DecidableEq

structure Entry where
  ident : String
  label : Label
  deps  : List String
  deriving Repr

/-! ## 1. Typed systems and typed processes  (CS-D1, CS-D3, CS-A2, CS-P1)

A system is a state type together with an observable type and an evaluation
map.  This is the type-theoretic shadow of CS-D1: it keeps *states* and
*observables* as separate data and refuses to identify a system with its
state space alone. -/

structure Sys (V : Type) where
  St  : Type
  Obs : Type
  ev  : Obs → St → V

/-- A typed process carries a forward map on states and a *pullback* on
observables, together with the coherence condition `CS-D3`
(`F^*(Obs_T) ⊆ Obs_S`, here rendered as a definitional equality of
readings rather than a subset condition). -/
structure Proc {V : Type} (S T : Sys V) where
  fwd  : S.St → T.St
  pull : T.Obs → S.Obs
  coh  : ∀ (o : T.Obs) (x : S.St), T.ev o (fwd x) = S.ev (pull o) x

/-- Extensionality for processes.  The coherence field is a `Prop`, so
processes agreeing on `fwd` and `pull` are equal by proof irrelevance. -/
theorem Proc.ext {V : Type} {S T : Sys V} :
    ∀ {f g : Proc S T}, f.fwd = g.fwd → f.pull = g.pull → f = g
  | ⟨_, _, _⟩, ⟨_, _, _⟩, rfl, rfl => rfl

/-- Identity process (half of CS-A2). -/
def Proc.idn {V : Type} (S : Sys V) : Proc S S :=
  { fwd := fun x => x, pull := fun o => o, coh := fun _ _ => rfl }

/-- Composition of typed processes (the other half of CS-A2).  Note that
the observable condition composes contravariantly, which is precisely the
step used in the proof of CS-P1. -/
def Proc.comp {V : Type} {S T U : Sys V} (f : Proc S T) (g : Proc T U) :
    Proc S U :=
  { fwd  := fun x => g.fwd (f.fwd x)
  , pull := fun o => f.pull (g.pull o)
  , coh  := by
      intro o x
      rw [g.coh o (f.fwd x), f.coh (g.pull o) x] }

/-! ### Category laws  (CS-P1)

These are the three equations asserted by CS-P1.  They hold definitionally
here because Lean 4 has eta for functions and for structures. -/

theorem Proc.idn_comp {V : Type} {S T : Sys V} (f : Proc S T) :
    Proc.comp (Proc.idn S) f = f := rfl

theorem Proc.comp_idn {V : Type} {S T : Sys V} (f : Proc S T) :
    Proc.comp f (Proc.idn T) = f := rfl

theorem Proc.comp_assoc {V : Type} {S T U W : Sys V}
    (f : Proc S T) (g : Proc T U) (h : Proc U W) :
    Proc.comp (Proc.comp f g) h = Proc.comp f (Proc.comp g h) := rfl

/-! ## 2. Parallel composition  (CS-D5, CS-P3)

The kinematical product.  Observables of the composite are generated by
observables of the factors; we model "generated by" in its minimal form,
namely the disjoint union of the two observable types.  This is weaker than
the algebra generated in CS-D5 and is flagged as such: the theorems below
concern only the embedding structure, not the algebra structure. -/

def Sys.par {V : Type} (S T : Sys V) : Sys V :=
  { St  := S.St × T.St
  , Obs := Sum S.Obs T.Obs
  , ev  := fun o x =>
      match o with
      | Sum.inl a => S.ev a x.1
      | Sum.inr b => T.ev b x.2 }

/-- Left projection is a typed process: this is the "observable embedding"
layer of CS-N1, isolated from the dynamical layer. -/
def Sys.projL {V : Type} (S T : Sys V) : Proc (Sys.par S T) S :=
  { fwd := fun x => x.1, pull := Sum.inl, coh := fun _ _ => rfl }

def Sys.projR {V : Type} (S T : Sys V) : Proc (Sys.par S T) T :=
  { fwd := fun x => x.2, pull := Sum.inr, coh := fun _ _ => rfl }

/-- Parallel composition of processes. -/
def Proc.par {V : Type} {S S' T T' : Sys V}
    (f : Proc S S') (g : Proc T T') : Proc (Sys.par S T) (Sys.par S' T') :=
  { fwd  := fun x => (f.fwd x.1, g.fwd x.2)
  , pull := fun o =>
      match o with
      | Sum.inl a => Sum.inl (f.pull a)
      | Sum.inr b => Sum.inr (g.pull b)
  , coh  := by
      intro o x
      cases o with
      | inl a => exact f.coh a x.1
      | inr b => exact g.coh b x.2 }

/-- Functoriality on identities. -/
theorem Proc.par_idn {V : Type} (S T : Sys V) :
    Proc.par (Proc.idn S) (Proc.idn T) = Proc.idn (Sys.par S T) :=
  Proc.ext rfl (funext (fun o => by cases o <;> rfl))

/-- Functoriality on composites (the interchange law). -/
theorem Proc.par_comp {V : Type} {S S' S'' T T' T'' : Sys V}
    (f : Proc S S') (f' : Proc S' S'') (g : Proc T T') (g' : Proc T' T'') :
    Proc.par (Proc.comp f f') (Proc.comp g g')
      = Proc.comp (Proc.par f g) (Proc.par f' g') :=
  Proc.ext rfl (funext (fun o => by cases o <;> rfl))

/-- The symmetry (swap) process. -/
def Sys.swap {V : Type} (S T : Sys V) : Proc (Sys.par S T) (Sys.par T S) :=
  { fwd  := fun x => (x.2, x.1)
  , pull := fun o =>
      match o with
      | Sum.inl b => Sum.inr b
      | Sum.inr a => Sum.inl a
  , coh  := by intro o x; cases o <;> rfl }

/-- Swap is an involution, so the symmetry is invertible.  This is the part
of CS-P3 that is available without the algebra structure. -/
theorem Sys.swap_swap {V : Type} (S T : Sys V) :
    Proc.comp (Sys.swap S T) (Sys.swap T S) = Proc.idn (Sys.par S T) :=
  Proc.ext rfl (funext (fun o => by cases o <;> rfl))

/-! ## 3. Nondegeneracy and generator factorization  (CS-L1, CS-T1, CS-C1)

We abstract the symplectic datum.  In the geometric setting, nondegeneracy
of `omega` says that `v ↦ omega(v, ·)` is a bundle isomorphism from tangent
vectors to covectors; the Hamiltonian vector field is the inverse image of
`dH`.  Here `Tan` stands for tangent data, `Cot` for cotangent data, and
`Nondeg` records exactly the bijection.

WHAT IS LOST: closedness `d omega = 0` has no counterpart below, so nothing
here distinguishes symplectic from merely almost-symplectic structure, and
no Jacobi identity is derived.  CS-L1's *closedness* half is therefore NOT
formalized; only its *nondegeneracy* half is. -/

structure Nondeg (Tan Cot : Type) where
  flat  : Tan → Cot
  sharp : Cot → Tan
  sharp_flat : ∀ t, sharp (flat t) = t
  flat_sharp : ∀ c, flat (sharp c) = c

/-- The generator assigned to a covector field, pointwise. -/
def Nondeg.gen {X Tan Cot : Type} (N : Nondeg Tan Cot)
    (dH : X → Cot) : X → Tan := fun x => N.sharp (dH x)

/-- Product of nondegenerate data: the nondegeneracy half of CS-L1. -/
def Nondeg.par {T1 C1 T2 C2 : Type}
    (N1 : Nondeg T1 C1) (N2 : Nondeg T2 C2) : Nondeg (T1 × T2) (C1 × C2) :=
  { flat  := fun t => (N1.flat t.1, N2.flat t.2)
  , sharp := fun c => (N1.sharp c.1, N2.sharp c.2)
  , sharp_flat := by
      intro t; simp [N1.sharp_flat, N2.sharp_flat]
  , flat_sharp := by
      intro c; simp [N1.flat_sharp, N2.flat_sharp] }

/-- A covector field on a product is *separable* when it is a pair of
fields pulled back from the two factors.  This is the abstraction of
"the Hamiltonian is additive": `d(h1 ∘ pi1 + h2 ∘ pi2) = (d h1, d h2)`. -/
def Separable {X Y C1 C2 : Type} (dH : X × Y → C1 × C2) : Prop :=
  ∃ (f : X → C1) (g : Y → C2), ∀ x y, dH (x, y) = (f x, g y)

/-- **Abstract CS-T1 / CS-C1.**  A separable covector field on a product
generates the pair of the generators of its parts.  The geometric theorem
CS-T1 is this statement plus the identification of `sharp` with the inverse
of `omega^flat` and of `dH` with an exterior differential. -/
theorem gen_par_of_separable
    {X Y T1 C1 T2 C2 : Type}
    (N1 : Nondeg T1 C1) (N2 : Nondeg T2 C2)
    (dH : X × Y → C1 × C2)
    (f : X → C1) (g : Y → C2)
    (hsep : ∀ x y, dH (x, y) = (f x, g y)) :
    ∀ x y, (N1.par N2).gen dH (x, y)
             = (N1.gen f x, N2.gen g y) := by
  intro x y
  show (N1.par N2).sharp (dH (x, y)) = _
  rw [hsep x y]
  rfl

/-- **Abstract CS-P4 (interaction is extra structure).**  Nondegeneracy and
the product decomposition do not determine the generator: there are
non-separable covector fields on the very same product. -/
theorem interaction_underdetermined :
    ∃ dH : Nat × Nat → Nat × Nat, ¬ Separable dH := by
  refine ⟨fun p => (p.2, 0), ?_⟩
  rintro ⟨f, _g, h⟩
  have h0 := congrArg Prod.fst (h 0 0)
  have h1 := congrArg Prod.fst (h 0 1)
  simp at h0 h1
  omega

/-- And separable fields do exist, so the two classes are both inhabited:
the kinematical product layer is strictly weaker than the dynamical
factorization layer (the CS-N1 separation, in its abstract form). -/
theorem separable_inhabited :
    ∃ dH : Nat × Nat → Nat × Nat, Separable dH :=
  ⟨fun p => (p.1, p.2), ⟨fun x => x, fun y => y, fun _ _ => rfl⟩⟩

/-! ## 4. Scalar reciprocity trichotomy  (HR-N1, HR-N2, S-N1)

For one degree of freedom per factor the coupling matrices of HR are
scalars, and matrix transposition is the identity, so HR-N1's reciprocity
condition `C21 = C12ᵀ` becomes `c21 = c12`.  We formalize the resulting
three-way classification and the invariance equation `a1 * c12 = a2 * c21`
established in HR-N2.

WHAT IS LOST: the derivation of `a1 * c12 = a2 * c21` from
`Aᵀ Ω₀ + Ω₀ A = 0` is a matrix computation carried out in the paper, not
here.  Below, that equation is taken as the *definition* of split-respecting
infinitesimal invariance. -/

inductive CouplingClass where
  | decoupled          -- c12 = c21 = 0 : dynamics factorizes (CS-C1)
  | reciprocalCoupled  -- c21 = c12 ≠ 0 : Hamiltonian, not factorized
  | nonReciprocal      -- c21 ≠ c12     : not Hamiltonian for omega-product
  deriving Repr, DecidableEq

def classify (c12 c21 : Int) : CouplingClass :=
  if c12 = 0 ∧ c21 = 0 then CouplingClass.decoupled
  else if c12 = c21 then CouplingClass.reciprocalCoupled
  else CouplingClass.nonReciprocal

theorem classify_decoupled_iff (c12 c21 : Int) :
    classify c12 c21 = CouplingClass.decoupled ↔ (c12 = 0 ∧ c21 = 0) := by
  unfold classify
  by_cases h : c12 = 0 ∧ c21 = 0
  · rw [if_pos h]
    exact ⟨fun _ => h, fun _ => rfl⟩
  · rw [if_neg h]
    constructor
    · intro h1
      by_cases h' : c12 = c21
      · rw [if_pos h'] at h1; exact absurd h1 (by decide)
      · rw [if_neg h'] at h1; exact absurd h1 (by decide)
    · intro h2; exact absurd h2 h

theorem classify_nonReciprocal_iff (c12 c21 : Int) :
    classify c12 c21 = CouplingClass.nonReciprocal ↔ c12 ≠ c21 := by
  unfold classify
  by_cases h : c12 = 0 ∧ c21 = 0
  · rw [if_pos h]
    obtain ⟨h1, h2⟩ := h
    constructor
    · intro hc; exact absurd hc (by decide)
    · intro hne; exact absurd (h1.trans h2.symm) hne
  · rw [if_neg h]
    by_cases h' : c12 = c21
    · rw [if_pos h']
      constructor
      · intro hc; exact absurd hc (by decide)
      · intro hne; exact absurd h' hne
    · rw [if_neg h']
      exact ⟨fun _ => h', fun _ => rfl⟩

/-- The three classes are exhaustive and mutually exclusive by
construction; each is realized. -/
theorem classify_examples :
    classify 0 0 = CouplingClass.decoupled ∧
    classify 3 3 = CouplingClass.reciprocalCoupled ∧
    classify 3 0 = CouplingClass.nonReciprocal := by
  refine ⟨?_, ?_, ?_⟩ <;> decide

/-- Integers have no zero divisors; proved from core lemmas only. -/
theorem int_no_zero_divisors {a b : Int} (ha : a ≠ 0) (hab : a * b = 0) :
    b = 0 := by
  have h : (a * b).natAbs = 0 := by rw [hab]; rfl
  rw [Int.natAbs_mul] at h
  rcases Nat.mul_eq_zero.mp h with h1 | h2
  · exact absurd (Int.natAbs_eq_zero.mp h1) ha
  · exact Int.natAbs_eq_zero.mp h2

/-- Split-respecting infinitesimal invariance, in the reduced form
established by the matrix computation of HR-N2. -/
def SplitInvariant (c12 c21 : Int) : Prop :=
  ∃ a1 a2 : Int, a1 ≠ 0 ∧ a2 ≠ 0 ∧ a1 * c12 = a2 * c21

/-- **Abstract HR-N2.**  A split-respecting invariant form exists exactly
when the two couplings vanish together. -/
theorem splitInvariant_iff (c12 c21 : Int) :
    SplitInvariant c12 c21 ↔ (c12 = 0 ↔ c21 = 0) := by
  constructor
  · rintro ⟨a1, a2, ha1, ha2, heq⟩
    constructor
    · intro h12
      rw [h12, Int.mul_zero] at heq
      exact int_no_zero_divisors ha2 heq.symm
    · intro h21
      rw [h21, Int.mul_zero] at heq
      exact int_no_zero_divisors ha1 heq
  · intro h
    by_cases h12 : c12 = 0
    · have h21 : c21 = 0 := h.mp h12
      exact ⟨1, 1, by decide, by decide, by rw [h12, h21]⟩
    · have h21 : c21 ≠ 0 := fun hc => h12 (h.mpr hc)
      exact ⟨c21, c12, h21, h12, Int.mul_comm c21 c12⟩

/-- **Abstract HR-C2 (unidirectional obstruction).**  If exactly one
coupling vanishes, no split-respecting invariant form exists. -/
theorem unidirectional_obstruction (c12 : Int) (h : c12 ≠ 0) :
    ¬ SplitInvariant c12 0 := by
  intro hs
  exact h ((splitInvariant_iff c12 0).mp hs |>.mpr rfl)

/-! ## 5. Protocols, observational equivalence, falsification
    (EL-D1, EL-D2, EL-P1, EL-N1, EL-D3, EL-P2, EL-T1, EL-C2)

A protocol is an index type of admitted (preparation, intervention,
measurement, time) tuples together with an outcome type for each index.

WHAT IS LOST: EL works with probability measures and total-variation
distance.  Here `Out i` is an arbitrary type and equality is exact, so only
EL's *exact* equivalence `~_P` is formalized; the tolerance relation
`~_{P,eps}` and its failure of transitivity are not. -/

structure Protocol where
  Idx : Type
  Out : Idx → Type

/-- A realization: a carrier, the state reached under each admitted index,
and the measurement read off at that index.  Carrier is a parameter, so
realizations over different carriers can be compared. -/
structure Realization (P : Protocol) (X : Type) where
  state : P.Idx → X
  meas  : (i : P.Idx) → X → P.Out i

def Realization.pred {P : Protocol} {X : Type}
    (R : Realization P X) (i : P.Idx) : P.Out i :=
  R.meas i (R.state i)

/-- EL-D2, exact case. -/
def ObsEq {P : Protocol} {X Y : Type}
    (R : Realization P X) (S : Realization P Y) : Prop :=
  ∀ i, R.pred i = S.pred i

/-- EL-P1: `~_P` is reflexive, symmetric and transitive. -/
theorem ObsEq.refl {P : Protocol} {X : Type} (R : Realization P X) :
    ObsEq R R := fun _ => rfl

theorem ObsEq.symm {P : Protocol} {X Y : Type}
    {R : Realization P X} {S : Realization P Y}
    (h : ObsEq R S) : ObsEq S R := fun i => (h i).symm

theorem ObsEq.trans {P : Protocol} {X Y Z : Type}
    {R : Realization P X} {S : Realization P Y} {T : Realization P Z}
    (h1 : ObsEq R S) (h2 : ObsEq S T) : ObsEq R T :=
  fun i => (h1 i).trans (h2 i)

/-- **Abstract EL-N1.**  Observational equivalence holds exactly when the
prediction maps coincide; hence the quotient by `~_P` is precisely the
image of the prediction map, and no finer distinction is available to `P`. -/
theorem obsEq_iff_pred_eq {P : Protocol} {X Y : Type}
    (R : Realization P X) (S : Realization P Y) :
    ObsEq R S ↔ (fun i => R.pred i) = (fun i => S.pred i) := by
  constructor
  · intro h; exact funext h
  · intro h i; exact congrFun h i

/-- `~_P` is strictly coarser than structural identity: two realizations
over the same carrier, with different states and different measurement
maps, can have identical predictions. -/
theorem obsEq_strictly_coarser :
    ∃ (P : Protocol) (R S : Realization P Nat), ObsEq R S ∧ R ≠ S := by
  refine ⟨⟨Unit, fun _ => Nat⟩,
          ⟨fun _ => 0, fun _ x => x⟩,
          ⟨fun _ => 1, fun _ x => x - 1⟩, ?_, ?_⟩
  · intro _; rfl
  · intro h
    have := congrFun (congrArg Realization.state h) ()
    exact absurd this (by decide)

/-- EL-D3: an isomorphism that *transports the interpretation*. -/
structure Transport {P : Protocol} {X Y : Type}
    (R : Realization P X) (S : Realization P Y) where
  F : X → Y
  state_ok : ∀ i, F (R.state i) = S.state i
  meas_ok  : ∀ i x, R.meas i x = S.meas i (F x)

/-- **Abstract EL-P2 (conditional bridge).**  Transporting the
interpretation implies observational equivalence. -/
theorem transport_obsEq {P : Protocol} {X Y : Type}
    {R : Realization P X} {S : Realization P Y}
    (t : Transport R S) : ObsEq R S := by
  intro i
  show R.meas i (R.state i) = S.meas i (S.state i)
  rw [t.meas_ok i (R.state i), t.state_ok i]

/-- Bijectivity, spelled out with an explicit two-sided inverse so that no
library beyond Lean core is required. -/
def IsBijection {X Y : Type} (F : X → Y) : Prop :=
  ∃ G : Y → X, (∀ x, G (F x) = x) ∧ (∀ y, F (G y) = y)

/-- **Abstract S-N2 (bare bijection is not enough).**  There are
realizations related by a bijection of carriers -- indeed by the identity
of the same carrier -- that are not observationally equivalent.  This is
the formal shadow of the mass-discrimination example: a symplectomorphism
of the closed systems exists, but it does not transport the port reading. -/
theorem bijection_not_sufficient :
    ∃ (P : Protocol) (R S : Realization P Nat),
      (∃ F : Nat → Nat, IsBijection F) ∧ ¬ ObsEq R S := by
  refine ⟨⟨Unit, fun _ => Nat⟩,
          ⟨fun _ => 1, fun _ x => x⟩,
          ⟨fun _ => 1, fun _ x => 2 * x⟩,
          ⟨fun x => x, ⟨fun y => y, fun _ => rfl, fun _ => rfl⟩⟩, ?_⟩
  intro h
  have h1 : (1 : Nat) = 2 := h ()
  exact absurd h1 (by decide)

/-- EL "protocol impoverishment": if every measurement is blind to the
state, then all realizations are observationally equivalent, and the
quotient of EL-N1 carries no state-discriminating information. -/
theorem blind_protocol {P : Protocol} {X Y : Type}
    (R : Realization P X) (S : Realization P Y)
    (c : (i : P.Idx) → P.Out i)
    (hR : ∀ i x, R.meas i x = c i) (hS : ∀ i y, S.meas i y = c i) :
    ObsEq R S := by
  intro i
  show R.meas i (R.state i) = S.meas i (S.state i)
  rw [hR, hS]

/-- EL-D5: a predeclared assessment rule that depends on the model only
through its protocol predictions. -/
structure Assessment (P : Protocol) where
  Datum  : P.Idx → Type
  accept : (i : P.Idx) → P.Out i → Datum i → Prop

def Accepts {P : Protocol} {X : Type}
    (A : Assessment P) (R : Realization P X)
    (i : P.Idx) (d : A.Datum i) : Prop :=
  A.accept i (R.pred i) d

/-- **Abstract EL-T1.**  Observationally equivalent realizations assessed
by a common rule have identical acceptance behaviour at every index. -/
theorem obsEq_same_acceptance {P : Protocol} {X Y : Type}
    {R : Realization P X} {S : Realization P Y}
    (A : Assessment P) (h : ObsEq R S)
    (i : P.Idx) (d : A.Datum i) :
    Accepts A R i d ↔ Accepts A S i d := by
  unfold Accepts
  rw [h i]

/-- **Abstract EL-C2 (protocol expansion).**  Differential falsification
refutes observational equivalence; equivalently, discriminating between
`~_P`-equivalent candidates requires changing some component of `P` or of
the assessment rule. -/
theorem differential_falsification {P : Protocol} {X Y : Type}
    {R : Realization P X} {S : Realization P Y}
    (A : Assessment P) (i : P.Idx) (d : A.Datum i)
    (h1 : Accepts A R i d) (h2 : ¬ Accepts A S i d) :
    ¬ ObsEq R S := by
  intro h
  exact h2 ((obsEq_same_acceptance A h i d).mp h1)

/-! ## 6. Claim registry

A machine-checked well-formedness condition on the synthesis paper's
dependency graph: every declared dependency must name a declared claim.
This checks bookkeeping only.  It does not check that any claim is true. -/

def registry : List Entry :=
  [ ⟨"S-A1", Label.assum,       []⟩
  , ⟨"S-A2", Label.axiomL,      []⟩
  , ⟨"S-E1", Label.empirical,   []⟩
  , ⟨"S-I1", Label.interp,      ["S-A2"]⟩
  , ⟨"S-D1", Label.defn,        ["S-A1"]⟩
  , ⟨"S-P1", Label.prop,        ["S-D1"]⟩
  , ⟨"S-L1", Label.lem,         ["S-D1"]⟩
  , ⟨"S-N1", Label.newResult,   ["S-D1", "S-L1"]⟩
  , ⟨"S-C1", Label.cor,         ["S-N1"]⟩
  , ⟨"S-P2", Label.prop,        ["S-N1"]⟩
  , ⟨"S-N2", Label.newResult,   ["S-D1", "S-P1"]⟩
  , ⟨"S-I2", Label.interp,      ["S-N2"]⟩
  , ⟨"S-C2", Label.cor,         ["S-N2"]⟩
  , ⟨"S-N3", Label.newResult,   ["S-N1"]⟩
  , ⟨"S-E2", Label.empirical,   []⟩
  , ⟨"S-E3", Label.empirical,   []⟩
  , ⟨"S-C3", Label.conj,        ["S-N1", "S-N2", "S-N3"]⟩
  ]

def declared (rs : List Entry) : List String := rs.map Entry.ident

def wellFormed (rs : List Entry) : Bool :=
  rs.all fun e => e.deps.all fun d => (declared rs).contains d

theorem registry_wellFormed : wellFormed registry = true := by decide

/-- No entry is labelled as a theorem or corollary without at least one
declared dependency: a syntactic guard against the failure mode "an
assumption silently promoted to a proved result". -/
def noFreeProofs (rs : List Entry) : Bool :=
  rs.all fun e =>
    match e.label with
    | Label.thm | Label.cor | Label.prop | Label.lem => !e.deps.isEmpty
    | _ => true

theorem registry_noFreeProofs : noFreeProofs registry = true := by decide

end Principia
